'use client';
import {useEffect,useState,useRef} from 'react';
import {Flower2,Search,ShoppingBag,ArrowUpRight,Plane,PackageCheck,ShieldCheck,Plus,Minus,ArrowRight,MapPin} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {examples,Product,money} from '@/lib/catalog';
export default function Store(){
const request = useRef<{requestId:string,token:string}|null>(null);

const [products,setProducts]=useState<Product[]>([]),[category,setCategory]=useState('Tất cả'),[query,setQuery]=useState(''),[sort,setSort]=useState('new'),[cart,setCart]=useState<Record<string,number>>({}),[modal,setModal]=useState(''),[selected,setSelected]=useState<Product|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<any>(null),[tracking,setTracking]=useState<any>(null),[loaded,setLoaded]=useState(false);
useEffect(()=>{fetch('/api/shop').then(r=>{if(!r.ok)throw Error();return r.json()}).then((d:any)=>{setProducts(d.products);setLoaded(true)}).catch(()=>setError('Không thể tải cửa hàng. Vui lòng tải lại trang.'));try{setCart(JSON.parse(localStorage.getItem('lotus-cart')||'{}'))}catch{}},[]);
useEffect(()=>{localStorage.setItem('lotus-cart',JSON.stringify(cart))},[cart]);
const lines=products.filter(p=>cart[p.id]&&p.active),total=lines.reduce((n,p)=>n+p.price*cart[p.id],0),count=lines.reduce((n,p)=>n+cart[p.id],0);
function add(p:Product){setCart(c=>({...c,[p.id]:Math.min((c[p.id]||0)+1,20)}));setSelected(null);setModal('cart')}
const filtered=products.filter(p=>(category==='Tất cả'||p.category===category)&&(p.name+' '+p.brand).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));request.current??={requestId:crypto.randomUUID(),token:crypto.randomUUID()};try{const r=await fetch('/api/shop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,items:lines.map(p=>({id:p.id,quantity:cart[p.id]})),...request.current})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setReceipt(d);request.current=null;setCart({});setModal('success')}catch(e:any){setError(e.message||'Không thể gửi. Vui lòng thử lại.')}finally{setBusy(false)}}
async function track(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setTracking(null);const f=new FormData(e.currentTarget);try{const r=await fetch('/api/shop?code='+encodeURIComponent(String(f.get('code')))+'&token='+encodeURIComponent(String(f.get('token'))));const d:any=await r.json();if(!r.ok)throw Error(d.error);setTracking(d)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
return <><div className="announcement">Một chút Mỹ, gửi trọn về Việt Nam <span>US → VN</span></div><header className="header"><a className="logo" href="/"><Flower2/>Lot<span>US</span><i>FROM THE US, WITH LOVE</i></a><nav><a href="#shop">Mua sắm</a><button onClick={()=>setModal('how')}>Cách đặt hàng</button><button onClick={()=>{setModal('track');setError('')}}>Tra cứu đơn hàng</button></nav><div className="header-right"><span>VN / USD</span><button className="bag" onClick={()=>{setModal('cart');setError('')}} aria-label="Giỏ hàng"><ShoppingBag size={21}/><b>{count}</b></button></div></header>
<main><section className="hero"><div className="hero-copy"><div className="eyebrow">CURATED IN THE US. DELIVERED TO YOU.</div><h1>Điều bạn thích ở Mỹ.<br/><em>Đến tay bạn ở Việt Nam.</em></h1><p>Khám phá những món đồ cho cuộc sống mỗi ngày.<br/>Bạn chọn điều mình thích. LotUS lo hành trình còn lại.</p><a className="primary" href="#shop">Khám phá sản phẩm <ArrowUpRight size={19}/></a><div className="hero-note"><Plane size={17}/> Từ Mỹ, gửi về nhà.</div></div><div className="hero-photo"><img src={examples[2].image} alt="Túi canvas màu kem trong ánh sáng tự nhiên"/><div className="photo-label"><span>THE EVERYDAY EDIT</span><strong>Những điều nhỏ.<br/>Niềm vui lớn.</strong></div><div className="photo-stamp">LotUS<br/><small>WITH LOVE ♡</small></div></div></section>
<div className="benefits"><span><ShoppingBag/> Chọn hàng từ Mỹ</span><span><PackageCheck/> Xác nhận trước khi mua</span><span><Plane/> Vận chuyển về Việt Nam</span><span><ShieldCheck/> Báo phí trước khi thanh toán</span></div>
<section id="shop" className="shop"><div className="section-title"><div className="eyebrow">THE LOTUS COLLECTION</div><h2>Một chút mới, cho mỗi ngày.</h2><p>Tìm món đồ bạn yêu thích, để LotUS mang về.</p></div><div className="catalog-toolbar"><div className="categories">{['Tất cả',...Array.from(new Set(products.map(p=>p.category)))].map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="search"><Search size={18}/><input aria-label="Tìm sản phẩm" placeholder="Tìm món bạn thích…" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="results"><span>{filtered.length} sản phẩm {products===examples?'· Bộ sưu tập minh họa':''}</span><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sắp xếp"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="new">Mới nhất</SelectItem><SelectItem value="low">Giá thấp đến cao</SelectItem><SelectItem value="high">Giá cao đến thấp</SelectItem></SelectContent></Select></div>
{error&&!modal&&<p role="alert" className="error">{error}</p>}<div className="product-grid">{filtered.map((p,i)=><article className="product" key={p.id}><button className={'product-image tone-'+i%4} onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/><span className="tag">{p.active?'Đặt từ Mỹ':'Xem trước'}</span><span className="image-action"><ArrowUpRight size={20}/></span></button><div className="brand">{p.brand}</div><button className="product-name" onClick={()=>setSelected(p)}>{p.name}</button><div className="price-row"><span>{money(p.price)}</span><button aria-label={'Xem '+p.name} onClick={()=>setSelected(p)}><Plus size={18}/></button></div></article>)}</div>{!loaded&&!error&&<p role="status">Đang tải sản phẩm…</p>}{loaded&&!filtered.length&&<div className="empty">Chưa tìm thấy món đồ phù hợp. Hãy thử từ khóa khác.</div>}{loaded&&products===examples&&<p className="sample-note">Bộ sưu tập minh họa • Sản phẩm và giá chưa mở bán. Hàng thật sẽ xuất hiện khi cửa hàng đăng sản phẩm.</p>}</section>
<section className="journey"><div><div className="eyebrow">A LITTLE CLOSER TO HOME</div><h2>Từ giỏ hàng ở Mỹ,<br/><em>đến cửa nhà bạn.</em></h2></div><div className="steps"><div><b>01</b><h3>Chọn món bạn thích</h3><p>Thêm sản phẩm và gửi yêu cầu đặt hàng.</p></div><div><b>02</b><h3>Xác nhận cùng LotUS</h3><p>Nhận báo giá gồm phí vận chuyển, thuế nếu có và thời gian dự kiến.</p></div><div><b>03</b><h3>Chờ món quà đến nhà</h3><p>Theo dõi hành trình đơn hàng bằng mã riêng.</p></div></div></section></main><footer><a className="logo" href="/"><Flower2/>Lot<span>US</span></a><p>Một chút Mỹ, gửi trọn về Việt Nam.</p><a href="/admin">Quản lý cửa hàng <ArrowUpRight size={14}/></a><small>© {new Date().getFullYear()} LotUS</small></footer>
<Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="modal"><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>{selected?.brand}</DialogDescription>{selected&&<><img className="detail-photo" src={selected.image} alt={selected.name}/><p>{selected.description}</p><strong>{money(selected.price)}</strong><p className="muted">Giá sản phẩm chưa gồm phí vận chuyển và thuế nếu có. LotUS sẽ báo tổng phí để bạn xác nhận.</p><Button disabled={!selected.active} onClick={()=>add(selected)}>{selected.active?'Thêm vào giỏ hàng':'Sản phẩm minh họa · Chưa mở bán'}</Button></>}</DialogContent></Dialog>
<Dialog open={!!modal} onOpenChange={v=>!v&&setModal('')}><DialogContent className="modal"><DialogTitle>{({cart:'Giỏ hàng của bạn',checkout:'Thông tin nhận hàng',success:'Đã nhận yêu cầu đặt hàng',track:'Theo dõi hành trình',how:'Đặt hàng cùng LotUS'} as any)[modal]}</DialogTitle><DialogDescription>{modal==='checkout'?'Chưa cần thanh toán. LotUS sẽ liên hệ xác nhận tổng phí.':'Từ Mỹ, gửi về nhà.'}</DialogDescription>
{modal==='cart'&&<>{!lines.length?<div className="empty"><ShoppingBag/><p>Giỏ hàng đang chờ món đồ bạn thích.</p></div>:lines.map(p=><div className="cart-line" key={p.id}><img src={p.image} alt=""/><div><strong>{p.name}</strong><p>{money(p.price)}</p><div className="quantity"><button aria-label="Giảm số lượng" onClick={()=>setCart({...cart,[p.id]:Math.max(0,cart[p.id]-1)})}><Minus size={16}/></button>{cart[p.id]}<button aria-label="Tăng số lượng" onClick={()=>setCart({...cart,[p.id]:Math.min(20,cart[p.id]+1)})}><Plus size={16}/></button></div></div></div>)}<div className="total"><span>Tạm tính</span><strong>{money(total)}</strong></div><p className="muted">Phí vận chuyển và thuế nếu có sẽ được báo trước khi thanh toán.</p><Button disabled={!count} onClick={()=>setModal('checkout')}>Tiếp tục đặt hàng <ArrowRight size={17}/></Button></>}
{modal==='checkout'&&<form onSubmit={submit} className="form"><label>Họ và tên<Input name="name" required maxLength={100}/></label><label>Số điện thoại tại Việt Nam<Input name="phone" required type="tel" pattern="[+0-9 ()-]{9,20}"/></label><label>Email<Input name="email" required type="email" maxLength={200}/></label><label>Địa chỉ đầy đủ tại Việt Nam<Input name="address" placeholder="Số nhà, đường, phường/xã, tỉnh/thành phố" required minLength={10} maxLength={500}/></label><label>Ghi chú (màu, kích cỡ…)<Input name="note" maxLength={1000}/></label><p>Tạm tính sản phẩm: <strong>{money(total)}</strong></p><p className="muted">Bằng việc gửi, bạn đồng ý để LotUS lưu thông tin nhận hàng và liên hệ xử lý đơn. Đây là yêu cầu đặt hàng; chỉ mua và thu tiền sau khi xác nhận.</p><Button disabled={busy}>{busy?'Đang gửi…':'Gửi yêu cầu đặt hàng'}</Button></form>}
{modal==='success'&&receipt&&<><PackageCheck size={40}/><p>Mã đơn: <strong>{receipt.code}</strong></p><p>Mã tra cứu riêng: <strong className="token">{receipt.token}</strong></p><p>Hãy lưu hai mã này. LotUS sẽ liên hệ với bạn để xác nhận chi phí và thời gian giao hàng.</p><Button onClick={()=>{setModal('track');setTracking(null)}}>Tra cứu đơn hàng</Button></>}
{modal==='track'&&<><form onSubmit={track} className="form"><label>Mã đơn hàng<Input name="code" required placeholder="LOT-…"/></label><label>Mã tra cứu riêng<Input name="token" required/></label><Button disabled={busy}>{busy?'Đang tìm…':'Tra cứu'}</Button></form>{tracking&&<div className="tracking"><MapPin/><h3>{tracking.status}</h3><p>{tracking.code}</p><p>{tracking.shipment||'Thông tin vận chuyển sẽ được cập nhật sau khi xác nhận đơn.'}</p><p>Tạm tính: {money(tracking.total)}</p></div>}</>}
{modal==='how'&&<><p>1. Chọn sản phẩm đang mở bán và thêm vào giỏ hàng.</p><p>2. Điền thông tin nhận hàng ở Việt Nam. Lưu mã đơn và mã tra cứu riêng.</p><p>3. LotUS liên hệ xác nhận tình trạng hàng, giá cuối cùng, phí vận chuyển, thuế nếu có, cách thanh toán và thời gian dự kiến. Bạn chỉ thanh toán sau khi đồng ý.</p><p>4. Tra cứu tiến độ khi LotUS mua và gửi hàng về Việt Nam.</p></>}{error&&<p role="alert" className="error">{error}</p>}</DialogContent></Dialog></>}
